blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/resendlabs/react-email/discussions
    about: Ask questions and discuss with other community members
  - name: Feature request
    url: https://github.com/resendlabs/react-email/discussions/new?category=ideas
    about: Feature requests should be opened as discussions
